# -*- coding: utf-8 -*-
"""music_kg.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nxwtOVrd9lQAh0USrilGofNya7IEUYIl
"""

!pip install kgtk

!pip install ampligraph

!echo "deb http://downloads.skewed.de/apt bionic main" >> /etc/apt/sources.list
!apt-key adv --keyserver keys.openpgp.org --recv-key 612DEFB798507F25
!apt-get update
!apt-get install python3-graph-tool python3-cairo python3-matplotlib
!apt-get install libcairo2-dev

import io
import os
import sys
import pandas as pd
import json
from kgtk.configure_kgtk_notebooks import ConfigureKGTK
from kgtk.functions import kgtk, kypher
 
df = pd.read_csv('triples.csv')
df = df.rename({'s' : "node1", 'p' : "label", 'o' : "node2"}, axis = 1)
df.index = df.node1
df = df.drop("node1", axis = 1)
df.reindex()
 
data_dir = '.'
df.to_csv(data_dir + "/triples.tsv", sep='\t')
extra_files_config = {"data": "triples.tsv"}
open(data_dir + '/extra_files.json', 'w').write(json.dumps(extra_files_config))
 
input_path = data_dir
output_path = data_dir
input_files_url = data_dir
project_name = 'Evan_project'
 
files = ["data"]
ck = ConfigureKGTK(files, input_files_url=input_files_url)
ck.configure_kgtk(input_graph_path=input_path,
                  output_path=output_path,
                  project_name=project_name,
                  json_config_file = data_dir + '/extra_files.json',)
 
ck.print_env_variables()
ck.load_files_into_cache()

kgtk(""" 
    head -i triples.tsv
""")

# Find the communities using blockmodel.
kgtk(""" 
    community-detection -i triples.tsv -o music_cluster.csv --method blockmodel
""")

